# Generated by Django 4.0.4 on 2022-06-29 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_appointment_patient_name_appointment_reschedule_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='patient_name',
            new_name='patient',
        ),
    ]
