# Generated by Django 4.0.4 on 2022-06-29 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_rename_patient_name_appointment_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='description',
            field=models.TextField(max_length=200),
        ),
    ]
