# Generated by Django 4.0.4 on 2022-07-16 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_user_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Archive',
            fields=[
                ('appointment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.appointment')),
                ('doctors_note', models.TextField(max_length=500)),
            ],
            bases=('main.appointment',),
        ),
    ]
