# Generated by Django 4.0.4 on 2022-07-16 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_archive'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Archive',
        ),
    ]
