# Generated by Django 4.0.4 on 2022-08-18 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_alter_user_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.CharField(choices=[('M', 'M'), ('F', 'F')], max_length=10, null=True),
        ),
    ]
