# Generated by Django 4.0.4 on 2022-08-24 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_alter_user_sex'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Staff',
        ),
    ]
